service: aws-node-twilio

provider:
  name: aws
  runtime: nodejs10.x
  config:
    accountSid:
    authToken:
  environment:
    TWILIO_ACCOUNT_SID: ${env:TWILIO_ACCOUNT_SID}
    TWILIO_AUTH_TOKEN: ${env:TWILIO_AUTH_TOKEN}
    # TWILIO_PHONE_NUMBER: YOUR-TWILIO-PHONE-NUMBER-HERE
plugins:
  - serverless-offline
package:
  exclude:
    - '*.test.js'

functions:
  sendText:
    handler: handler.sendText
    events:
      - http:
          path: api/sendText
          method: post
          integration: lambda
          cors: true
