/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:a5af299e-4594-4d42-8f43-01a0eb849e79",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_Dr43SFDZq",
    "aws_user_pools_web_client_id": "49r1j3au6cos8jrat2747a7dsn",
    "oauth": {},
    "aws_dynamodb_all_tables_region": "us-east-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "teachersdb-dev",
            "region": "us-east-1"
        }
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "teachersapi",
            "endpoint": "https://p9bw7z60z7.execute-api.us-east-1.amazonaws.com/dev",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
