/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:170b9125-211a-433c-92c0-378107cd46a6",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_ETiJOG458",
    "aws_user_pools_web_client_id": "7rvq02tt0db1bhvm7pa6t1dc42",
    "oauth": {},
    "aws_dynamodb_all_tables_region": "us-east-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "teachers-dev",
            "region": "us-east-1"
        }
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "restAPI",
            "endpoint": "https://6q53uyucbl.execute-api.us-east-1.amazonaws.com/dev",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
