const columns = [
  { accessor: 'studentFirstName', Header: 'Student First Name' },
  { accessor: 'studentLastName', Header: 'Student Last Name' },
  { accessor: 'studentGender', Header: 'Gender' },
  { accessor: 'studentBirthday', Header: 'Birthday' },
  { accessor: 'emergencyContact', Header: 'Emergency Contact'},
  { accessor: 'emergencyContactPhoneNumber', Header: 'Emergency Contact Number' },
  { accessor: 'address', Header: 'Address' },
  { accessor: 'address2', Header: 'address 2' },
  { accessor: 'city', Header: 'City' },
  { accessor: 'state', Header: 'State' },
  { accessor: 'zipCode', Header: 'Zipcode' },
  { accessor: 'ethnicities', Header: 'Ethnicity'},
  { accessor: 'primaryLanguage', Header: 'Primary Language' },
  { accessor: 'currentSchool', Header: 'currentSchool' },
  { accessor: 'currentGrade', Header: 'currentGrade' },
  { accessor: 'summerSchool', Header: 'Summer School' },
  { accessor: 'mnpsId', Header: 'MNPS Id' },
  { accessor: 'needTransportation', Header: 'Need Transportation' },
  { accessor: 'needMedicine', Header: 'Need Medicine' },
  { accessor: 'medicineConditionDesc', Header: 'Notes on Medicine' },
  { accessor: 'hasAllergies', Header: 'Allergies?' },
  { accessor: 'allergiesList', Header: 'Notes on Allergies' },
  { accessor: 'householdNumber', Header: 'Household Number' },
  { accessor: 'grossIncome', Header: 'Income' },
  { accessor: 'date', Header: 'Registration Date' },
  { accessor: 'guardian1FirstName', Header: 'Guardian 1 First Name' },
  { accessor: 'guardian1LastName', Header: 'Guardian 1 Last Name' },
  { accessor: 'guardian1PhoneNumber', Header: 'Guardian 1 Phone Number' },
  { accessor: 'guardian1Relationship', Header: 'Guardian 1 Relationship' },
  { accessor: 'guardian1email', Header: 'Guardian 1 email' },
  { accessor: 'guardian2FirstName', Header: 'Guardian 2 First Name' },
  { accessor: 'guardian2LastName', Header: 'Guardian 2 Last Name' },
  { accessor: 'guardian2PhoneNumber', Header: 'Guardian 2 Phone Number' },
  { accessor: 'guardian2Relationship', Header: 'Guardian 2 Relationship' },
  { accessor: 'guardian2email', Header: 'Guardian 2 email' },
  { accessor: 'guardian3FirstName', Header: 'Guardian 3 First Name' },
  { accessor: 'guardian3LastName', Header: 'Guardian 3 Last Name' },
  { accessor: 'guardian3PhoneNumber', Header: 'Guardian 3 Phone Number' },
  { accessor: 'guardian3Relationship', Header: 'Guardian 3 Relationship' },
  { accessor: 'guardian3email', Header: 'Guardian 3 Email' },
  { accessor: 'consent', Header: 'consent' },
]

export default columns
