const columns = [
  { accessor: 'address', Header: 'Address' },
  { accessor: 'address2', Header: 'address 2' },
  { accessor: 'city', Header: 'City' },
  { accessor: 'consent', Header: 'consent' },
  { accessor: 'currentGrade', Header: 'currentGrade' },
  { accessor: 'currentSchool', Header: 'currentSchool' },
  { accessor: 'date', Header: 'Date' },
  { accessor: 'emergencyContactPhoneNumber', Header: 'Emergency Contact' },
  { accessor: 'grossIncome', Header: 'Income' },
  { accessor: 'guardian1FirstName', Header: 'Guardian First Name' },
  { accessor: 'guardian1LastName', Header: 'Guardian Last Name' },
  { accessor: 'guardian1PhoneNumber', Header: 'Guardian Phone Number' },
  { accessor: 'guardian1Relationship', Header: 'Guardian Relationship' },
  { accessor: 'guardian1email', Header: 'Guardian email' },
  { accessor: 'guardian2FirstName', Header: 'Guardian First Name' },
  { accessor: 'guardian2LastName', Header: 'Guardian Last Name' },
  { accessor: 'guardian2PhoneNumber', Header: 'Guardian Phone Number' },
  { accessor: 'guardian2Relationship', Header: 'Guardian Relationship' },
  { accessor: 'guardian2email', Header: 'Guardian email' },
  { accessor: 'guardian3FirstName', Header: 'Guardian First Name' },
  { accessor: 'guardian3LastName', Header: 'Guardian Last Name' },
  { accessor: 'guardian3PhoneNumber', Header: 'Guardian Phone Number' },
  { accessor: 'guardian3Relationship', Header: 'Guardian Relationship' },
  { accessor: 'guardian3email', Header: 'Guardian Email' },
  { accessor: 'hasAllergies', Header: 'Allergies?' },
  { accessor: 'householdNumber', Header: 'Household Number' },
  { accessor: 'mnpsId', Header: 'MNPS Id' },
  { accessor: 'needMedicine', Header: 'Need Medicine' },
  { accessor: 'needTransportation', Header: 'Need Transportation' },
  { accessor: 'primaryLanguage', Header: 'Primary Language' },
  { accessor: 'state', Header: 'State' },
  { accessor: 'studentBirthday', Header: 'Birthday' },
  { accessor: 'studentFirstName', Header: 'Student First Name' },
  { accessor: 'studentGender', Header: 'Gender' },
  { accessor: 'studentLastName', Header: 'Student Last Name' },
  { accessor: 'summerSchool', Header: 'Summer School' },
  { accessor: 'zipCode', Header: 'Zipcode' }
]

export default columns
