/* eslint-disable */
// this is an auto generated file. This will be overwritten

export const onCreateStudent = /* GraphQL */ `
  subscription OnCreateStudent {
    onCreateStudent {
      id
      parent1FirstName
      parent1LastName
      parent2FirstName
      parent2LastName
      parent3FirstName
      parent3LastName
      parent1phoneNumber
      parent2phoneNumber
      parent3phoneNumber
      parent1Email
      parent2Email
      parent3Email
      ethnicities
      grossIncome
      householdNumber
      address
      address2
      allergiesList
      city
      currentGrade
      currentSchool
      emergencyContact
      emergencyContactPhoneNumber
      hasAllergies
      medicineDesc
      mnpsId
      needMedication
      needTransportation
      primaryLanguage
      relationship
      studentFirstName
      studentLastName
      studentBirthday
      studentGender
      summerSchool
      createdAt
      updatedAt
    }
  }
`;
export const onUpdateStudent = /* GraphQL */ `
  subscription OnUpdateStudent {
    onUpdateStudent {
      id
      parent1FirstName
      parent1LastName
      parent2FirstName
      parent2LastName
      parent3FirstName
      parent3LastName
      parent1phoneNumber
      parent2phoneNumber
      parent3phoneNumber
      parent1Email
      parent2Email
      parent3Email
      ethnicities
      grossIncome
      householdNumber
      address
      address2
      allergiesList
      city
      currentGrade
      currentSchool
      emergencyContact
      emergencyContactPhoneNumber
      hasAllergies
      medicineDesc
      mnpsId
      needMedication
      needTransportation
      primaryLanguage
      relationship
      studentFirstName
      studentLastName
      studentBirthday
      studentGender
      summerSchool
      createdAt
      updatedAt
    }
  }
`;
export const onDeleteStudent = /* GraphQL */ `
  subscription OnDeleteStudent {
    onDeleteStudent {
      id
      parent1FirstName
      parent1LastName
      parent2FirstName
      parent2LastName
      parent3FirstName
      parent3LastName
      parent1phoneNumber
      parent2phoneNumber
      parent3phoneNumber
      parent1Email
      parent2Email
      parent3Email
      ethnicities
      grossIncome
      householdNumber
      address
      address2
      allergiesList
      city
      currentGrade
      currentSchool
      emergencyContact
      emergencyContactPhoneNumber
      hasAllergies
      medicineDesc
      mnpsId
      needMedication
      needTransportation
      primaryLanguage
      relationship
      studentFirstName
      studentLastName
      studentBirthday
      studentGender
      summerSchool
      createdAt
      updatedAt
    }
  }
`;
